"""Posouzení slibů, stav 20. 9. 2026. Všechna znění jsou parafráze.

Výběr: hlavní tematické kapitoly vlastního aktuálního programu, konkrétní
závazky v nich. Nevydáváme redakční výběr za analýzu četnosti reklamy.
Pole references obsahuje (ID archivovaného pramene, přesný lokátor).
"""
DATE = '2026-09-20'
AUTH = 'e4f8e48e77fd9841'
STATUT = '92070caf8da6904e'
HOUSING = 'bcabc7c6ac31af4e'
CORRECTION = '45bee869fd2c38ad'
MHD = '0f370d838d2a82a6'
RAIL = '950f39946cb6bdf8'
HEAT = '162b40e70de36f42'
WASTE = 'ebf1698caaa4b1ce'
STADIUM = '5097c0bac5a5fffc'
LOAN = '54680ebc827751f8'

# Stejná právní východiska; konkrétní překážky jsou u jednotlivých závazků.
COMPETENCES = {
 'housing': ('Město může investovat do vlastního bydlení, rozhodovat o majetku a pravidlech; u svěřených bytů musí zapojit městské části. Soukromou výstavbu nemůže jednoduše nařídit.', [(STATUT, 'část o majetku města a bytovém hospodářství'), (AUTH, 'pravomoci zastupitelstva a rady')]),
 'budget': ('Městské zastupitelstvo může změnit rozpočet a financovat městské služby. Konkrétní výdaj potřebuje schválení a opakované krytí v dalších letech.', [(AUTH, 'rozpočet, příspěvkové organizace a hospodaření')]),
 'transport': ('Město ovlivňuje vlastní dopravu a její financování. Změny integrovaného tarifu, regionálních spojů a státních staveb vyžadují další partnery.', [(STATUT, 'doprava'), (MHD, 'tarif IDS JMK a dotace na roční šalinkartu')]),
 'rail': ('Město připravuje své pozemky, území a návaznou MHD; železniční uzel připravuje Správa železnic. Samotná brněnská koalice nerozhodne o celé státní investici.', [(RAIL, 'schválený záměr projektu; spolupráce města a Správy železnic')]),
 'energy': ('Vlastnictví městských společností dává městu vliv, ale nenahrazuje rozhodování společnosti, investiční financování, soutěže ani cenová pravidla.', [(AUTH, 'rozhodování ve věcech obce jako jediného společníka'), (STATUT, 'majetek města')]),
 'public': ('Město může upravovat své veřejné prostory a financovat údržbu. Zásahy do ulic závisí také na správě sítí, vlastnictví pozemků a povolování.', [(STATUT, 'životní prostředí, doprava a majetek')]),
 'transparency': ('Zastupitel může přímo ovlivnit vlastní hlas. Změna městských pravidel, zadání auditu nebo zveřejňování dalších údajů potřebuje podporu příslušného orgánu.', [(AUTH, 'pravomoci zastupitelstva a rady')]),
 'referendum': ('Místní referendum může zavázat město v jeho samostatné působnosti. Nemůže samo přikázat státu přesun železniční investice.', [('a19e254790b698b5', 'samostatná působnost a nepřípustné otázky'), ('9f15c393436e0c6f', 'vyhlášení zastupitelstvem')]),
}

CAMPAIGNS = {
 1: dict(summary='Program zatím pojmenovává oblasti, ale nedává konkrétní závazky, podle kterých by šlo poznat splnění.', selection='Jediný doložený společný rámec z aktuálního oznámení; zdravotnictví, školství a služby nesplňují podmínky tří konkrétních slibů.', political='Bez vlastních zastupitelů z období 2022–2026; hlasování bývalých členů SOCDEM nelze připsat této kandidátce.'),
 2: dict(summary='Bydlení má přípravné kroky i rozpory v prodejích; levnější MHD stojí na nejistém přílivu nově přihlášených obyvatel.', selection='Bydlení a MHD jsou explicitní priority úvodu programu; doplňujeme komunikaci a energetiku. Opravy, novostavby, prodeje a audit posuzujeme jako jeden bytový balík.', political='Dnešní kandidáti mají zkušenost s prosazováním rozpočtu a bytových projektů; to neprokazuje většinu pro nový tarif MHD.'),
 3: dict(summary='Otevřené hlasování má osobní oporu v minulosti, ale slíbené byty a levnější MHD zatím nemají doloženou úplnou cestu k realizaci.', selection='Výběr z kapitol bydlení, doprava, zeleň a otevřená radnice; odděleně vlastní hlasování a navýšení participativního rozpočtu.', political='Tři dnešní kandidáti mají celoměstskou praxi; shoda s jinými programy na bydlení či MHD není koaliční dohoda.'),
 4: dict(summary='Sportovní příspěvek lze zavést, u privatizací je postoj neurčitý a minulé hlasy nedokazují prosazení lanovky.', selection='Konkrétní závazky ze tří hlavních oblastí zveřejněného programu: doprava, bydlení a sport.', political='Z nynější kandidátky mají historii mandátu tři lidé, ne celý původní klub ANO; Trojan v září připouští spolupráci s ODS i Piráty, žádná většina tím není dohodnuta.', political_refs=[('d72a4ff0bf23c5a5', 'rozhovor: možnost spolupráce s ODS a Piráty')]),
 5: dict(summary='Stadion má podporu napříč zastupitelstvem, ale stále vyžaduje vyřešit právní a finanční podmínky; 2 000 bytů je cíl až do roku 2035.', selection='Stadion je výslovně hlavní strategický cíl; přidáváme bytovou kapitolu a konkrétní kontrolní závazek z části o správě města.', political='Podmíněnou podporu stadionu v září 2025 vyslovilo 50 zastupitelů; jde o podporu projektu s podmínkami, ne příslib koalice se Za Lužánky.'),
 6: dict(summary='Kandidáti doložitelně podpořili financování arény a přípravu bydlení, dokončení dalších staveb však vyžaduje více než dosavadní hlasy.', selection='Konkrétní závazky z kapitol bydlení, sport, rozvoj, zeleň a kultura; nová lídryně není autorkou hlasování dosavadních zastupitelů.', political='Na listině je jedenáct současných zastupitelů; jejich dosavadní vliv neznamená stejnou sílu po volbách. Veřejný výrok lídra ANO nevylučuje budoucí spolupráci.', political_refs=[('d72a4ff0bf23c5a5', 'možná spolupráce ANO a ODS')]),
 7: dict(summary='Byty, MHD a sociální služby město ovlivnit může, program ale neurčuje rozsah a financování; lídr má starší zastupitelskou zkušenost.', selection='Bydlení, přímá sociální pomoc a doprava tvoří samostatné programové kapitoly; nerozdělujeme obecná hesla na uměle početné sliby.', political='Absence mandátu v posledním období neznamená začátečníka: Martin Říha působil v dřívějším celoměstském zastupitelstvu.'),
 8: dict(summary='Příprava bydlení je doložená, ale další tisíc bytů není tisíc hotových bytů a přesun státních peněz z nádraží město samo nezařídí.', selection='Výběr pokrývá všech pět pilířů programu: bydlení, veřejný prostor, dopravu, život ve městě a vodu; nádraží a tarif sdružujeme pod dopravu.', political='Devět dnešních kandidátů má současný mandát, většinou získaný původně za ANO; jejich historii přičítáme lidem, ne novému názvu automaticky.'),
 9: dict(summary='Obecné priority bez brněnských cílů neumožňují poznat splnění; lídr přitom má i starší zkušenost městského radního.', selection='Pouze doložený celostátní komunální rámec a představení brněnského lídra; nevytváříme tři místní sliby, které strana takto nezveřejnila.', political='Tomáš Kratochvíl není nováček: v roce 2014 se stal městským radním; nezaměňujeme ho se současným radním Petrem Kratochvílem.'),
10: dict(summary='Útulky a kastrace lze podpořit z města, plošný zákaz pyrotechniky má právní meze a tři kandidátky potřebují spojence.', selection='Tři konkrétní nástroje z komunálního prohlášení výslovně zahrnujícího Brno: útulky, kastrace a pyrotechnika; nejde o místní detailní program.', political='Registrovány jsou jen tři kandidátky: ani jejich zvolení nemůže samo vytvořit většinu v 55členném zastupitelstvu.'),
11: dict(summary='Referendum lze za zákonných podmínek vyhlásit, jeho výsledek však sám nepřesune státní nádraží.', selection='Jediný aktuálně datovaný požadavek pro rok 2026; starší webový program nebyl automaticky převzat.', political='K vyhlášení referenda zastupitelstvem je třeba většina; existuje i občanská cesta. Počet budoucích mandátů B3! není doložen.'),
12: dict(summary='Vokřál má doloženou starší praxi, ale sleva na teplo, příjmové nájemné a investice do zoo zatím postrádají ověřené společné finanční krytí.', selection='Číselné závazky z kapitol energie, bydlení, zoo a bezpečnost; třetí kotel je samostatný velký projekt.', political='Bývalý primátor přináší zkušenost z vedení města; nový mandát a koaliční podporu z toho nelze odvodit.'),
13: dict(summary='Poplatky město změnit může, ale jejich zrušení neuhradí odvoz odpadu; doložená starší kontrolní praxe nenahrazuje rozpočet.', selection='Tři viditelné samostatné programové stránky: parkování, odpady a finance; kontrola se týká velkých investic, nikoliv automatického odmítání každé stavby.', political='Klára Liptáková dříve působila jako náměstkyně; letošní kandidátce nepřipisujeme hlasy celé bývalé koalice SPD a Trikolory.'),
14: dict(summary='Sedláček zná přípravu města, ale 500 městských bytů ročně a velké stavby potřebují doložený harmonogram, peníze i další investory.', selection='Pět výrazných závazků programu: byty, doprava, seniorské kapacity, školy a pracovní místa; objem výstavby nezaměňujeme za přípravu.', political='Působení v Kanceláři architekta města dokládá odbornou roli, nikoliv zkušenost se získáváním většiny v zastupitelstvu.'),
15: dict(summary='Odpor k prodeji bytů odpovídá minulým hlasům, u výstavby, kotle a stadionu však zůstávají investiční a politické podmínky.', selection='Výběr z dopravy, bydlení, energetiky a sportu; parkovací příjmy jsou samostatný konkrétní rozpočtový závazek.', political='Tři dnešní kandidáti mají městský mandát a u konkrétních návrhů se přidávali k širší většině. Nová většina ani role ve vedení nejsou doložené.'),
16: dict(summary='Více strážníků, úklid a stacionář jsou ovlivnitelné městem, ale chybí konkrétní kapacity, personální plán a financování.', selection='Tři konkrétní priority ze zahájení kampaně 31. srpna: strážníci, nepřetržitý úklid a stacionář; starý program 2022 nepřebíráme.', political='Kment a Prokeš mají osobní hlasovací historii; bez návrhu personálu a provozu nelze z jejich rozpočtových hlasů potvrdit tyto nové služby.'),
}

CLAIMS=[]
def add(key, title, why, competence, practical, change, signal='Nový závazek', refs=(), history='', counter='', promise=None, source=None, locator=None, votes=None):
    CLAIMS.append(dict(key=key,title=title,why=why,competence=competence,practical=practical,change=change,signal=signal,references=list(refs),history=history,counter=counter,promise=promise,source=source,locator=locator,votes=votes))

add('K01-01','Zdravotnictví, školy a služby','Není řečeno, jakou službu, v jakém rozsahu a do kdy mají voliči dostat.','budget','Bez konkrétního opatření nelze spočítat náklady ani posoudit, zda jde o městské zdravotnictví či školství, nebo o působnost jiného zřizovatele.','Aktuální brněnský program s cíli, termíny a odpovědností.',signal='Málo konkrétní',counter='Úzký dohledaný rámec není důkaz, že kandidáti nemají žádné návrhy.')
add('K02-01','Roční MHD pro dospělé za 1 000 Kč','Sleva má deklarovaný výpočet, ale její zaplacení závisí na lidech, které město nepřinutí přihlásit trvalý pobyt.','transport','Program odhaduje čistý dopad na 250–400 mil. Kč ročně a počítá s přibližně 10 tisíci nově přihlášených; jde o předpoklad kampaně. DPMB uvádí základní roční cenu 4 750 Kč a příspěvek 1 425 Kč pro oprávněné žadatele. Ceník a dotace nejsou totéž.','Citlivostní rozpočet pro menší počet nových obyvatel, dohoda o tarifu a schválené krytí.',refs=[(MHD,'roční jízdenka pro zóny 100+101; příspěvek 1 425 Kč')],counter='Město už umí jízdné dotovat; sleva tedy není sama o sobě nemožná.')
add('K02-02','800 opravených a až 1 000 nových bytů','Existují připravené projekty, ale součet prázdných bytů není seznam rychle opravitelných bytů a příprava není dokončení.','housing','Program spojuje opravy do čtyř let, nové byty pomocí PPP a modulů, konec prodejů a audit družstev. Lednový městský údaj o 870 volných svěřených bytech byl v březnové tabulce opraven na 1 462; starý součet s 62 nesvěřenými byty proto není spolehlivý výchozí stav.','Seznam bytů a projektů s termíny, rozpočtem a stavem povolení; audit a vyjasnění pravidel prodeje.',signal='Smíšená praxe',refs=[(HOUSING,'PDF s. 8 – původní údaj a důvody neobsazení'),(CORRECTION,'PDF s. 7–10 – dotaz Drápalové a opravená tabulka'),(LOAN,'PDF s. 1 – zářijový návrh úvěru, ne důkaz přijetí')],history='Osm nynějších kandidátů podpořilo prodej Dornychu 29/31, osm později zrušení starého privatizačního postupu. Podporovali také financování přípravy Kamenného vrchu.',counter='Lednové omezení privatizace je skutečný posun. Audit projektu, který dříve podporovali, není sám o sobě rozpor.',promise='Do čtyř let opravit 800 volných bytů, přes PPP a moduly vybudovat až 1 000 nových; ukončit prodej bytových domů a prověřit družstevní projekty.',votes=['Z9-25-057','Z9-32-036','Z9-36-071'])
add('K02-05','Dokončit třetí kotel SAKO','Postoj k veřejnosti hlasování neprokazuje podporu samotné investice ani její dokončení.','energy','Je třeba ověřit finální zakázku, financování, povolení a termín zprovoznění; tyto podklady zde netvoří uzavřený investiční audit.','Doložený aktuální investiční harmonogram, smlouva a financování.',signal='Jen nepřímý důkaz',counter='Odmítnutí tajné volby je doložené, následný tajný hlas jednotlivců však neznáme.')
add('K02-06','Odpověď na každý podnět','Proces město zavést může, zatím ale není doloženo, jak bude garantovat termíny a odpovědnost.','budget','Program do dvou let slibuje odpověď, termín a odpovědnou osobu u každého podnětu. Rozhodující bude evidence, personální kapacita a zveřejnění plnění.','Veřejná pravidla lhůt, odpovědností a statistiky vyřízení.',promise='Do dvou let zavést systém, v němž každý podnět dostane odpověď, termín a odpovědnou osobu.',source='a5c21a6ba96acdd7',locator='Město, které komunikuje – Do 2 let',history='Přímý celoměstský výsledek odpovídající této garanci není v ověřeném výběru doložen.',counter='Jde o organizační změnu, ne o slib závislý na státní megastavbě.')
add('K03-01','800 oprav a tempo 300–400 nových bytů','Kontrola bytového fondu je doložená, slíbené tempo výstavby však není doloženým výsledkem.','housing','Tempo 300–400 nových bytů se vztahuje až ke konci období. Nejde o 400 bytů každý rok. U oprav záleží na technickém stavu a spolupráci městských částí.','Projektový seznam, financování a každoroční rozlišení oprav, zahájených a dokončených bytů.',signal='Doložená kontrola',refs=[(CORRECTION,'PDF s. 7–10 – Drápalová upozornila na chybu součtu bytů')],history='Jana Drápalová v lednu 2026 upozornila na nesprávný součet neobsazených bytů; březnová odpověď obsahuje opravenou tabulku.',counter='Kontrola dat je konkrétní práce, sama ale nové byty nepostaví.')
add('K03-02','MHD zdarma pro děti, studenty a seniory','Město může slevu financovat, ale není doloženo krytí výpadku tržeb pro všechny slibované skupiny.','transport','Dnes má část těchto cestujících snížený tarif a někteří již jezdí zdarma. Je nutné počítat jen nové slevy, jejich věkové hranice a rozsah zón.','Ověřený propočet nově zvýhodněných cestujících a schválená kompenzace.',refs=[(MHD,'snížená roční cena a bezplatná přeprava')],counter='Existující systém slev usnadňuje provedení; nejde o technicky nový způsob přepravy.')
add('K03-03','Nepodporovat tajná hlasování','Dosavadní osobní hlasy tomuto závazku odpovídají, ale volební zastoupení celé nové kandidátky zůstává nejisté.','transparency','Vlastní hlas mají případní zastupitelé pod kontrolou a nepotřebují rozpočtovou většinu. Silný důkaz pro chování dvou lidí není zárukou jednání všech nově zvolených.', 'Veřejný závazek všech zvolených a sledování každého dalšího procedurálního hlasu.',signal='Soulad s hlasováním',history='Drápalová a Flamiková 18. 10. 2023 odmítly tajné hlasování o SAKO. Vencálek tehdy neměl mandát.',counter='Z tohoto důkazu nelze vyvodit, jak někdo hlasoval v následném tajném hlasování.')
add('K03-04','50 milionů na Dáme na vás','Participativní rozpočet už funguje, ale vznik fondu nepotvrzuje podporu částky 50 milionů.','budget','Je třeba odlišit roční alokaci pro nové návrhy od čerpání rozpracovaných projektů. Peníze navíc soutěží s bydlením, dopravou a dalšími prioritami.','Schválená roční částka 50 mil. Kč a pravidla započítávání projektů.',signal='Existující nástroj',counter='Není třeba zakládat participaci od nuly; důkaz se týká nižší úrovně závazku.')
add('K03-06','Více stromů a stínu v ulicích','Město umí výsadbu zadávat, ale plošný výsledek vyžaduje prostor pro kořeny, sítě a následnou péči.','public','Samotný počet vysazených stromů není plocha skutečného stínu; ověření vyžaduje místa výsadby, přežití stromů a péči.','Seznam ulic, rozpočet péče a měření stínu.',promise='Rozvíjet zeleň, zadržování vody a stín ve městě.',source='7a6b0de97db9da61',locator='kapitola 04 Zeleň, voda a stín ve městě',signal='Obecný cíl',history='Přímý souhrnný výsledek odpovídající této formulaci nebyl v podkladech prokázán.',counter='Podrobná kapitola obsahuje konkrétnější nástroje; hodnotíme jen tento vybraný hlavní směr.')
add('K04-01','Rozvoj tramvají a lanovka','Dřívější hlas o projednání analýz neříká, zda kandidáti lanovku postaví.','transport','Tramvajové tratě a lanovka mají odlišné náklady, povolení a dopravní přínosy. Bez samostatného finančního a povolovacího rozboru nelze doložit cestu k celému závazku.','Aktuální harmonogram a krytí konkrétních staveb.',signal='Jen nepřímý důkaz',counter='Nehlasování o veřejném projednání není hlas proti lanovce; vzetí petice na vědomí také ne.')
add('K04-02','Stop „zbytečným“ privatizacím','Není určeno, které prodeje jsou zbytečné, a dosavadní osobní hlasy ukazují prodej i pozdější omezení privatizace.','housing','Bez definice výjimek lze stejný převod vydávat za soulad i nesoulad s programem. Město má pravomoc o prodeji rozhodovat.','Seznam přípustných výjimek a závazná pravidla prodeje.',signal='Smíšená praxe',counter='Nové omezení privatizace může být změnou politiky; starý prodej sám neprokazuje nepravdivý budoucí slib.')
add('K04-03','1 000 Kč ročně dětem na sport','Existuje příbuzný systém voucherů, nikoli doklad schválení tohoto nového nároku.','budget','Náklady jsou 1 000 Kč krát počet oprávněných dětí plus správa. Program musí vymezit věk, pobyt, čerpání a vztah k dosavadní podpoře.','Pravidla nároku, počet příjemců a rozpočtové krytí.',signal='Existující nástroj',counter='Příbuzný program snižuje organizační nejistotu; neprokazuje financování nové částky.')
add('K05-01','Stadion za Lužánkami','Široká podpora stadionu je doložená, jeho finální právní a finanční podoba však není totéž co podmíněný souhlas.','budget','Zářijový materiál předkládá tři varianty dalšího postupu a nové posudky. Samotná předloha není přijaté usnesení. Modernizace Srbské je další výdaj do dokončení.','Ověřené konečné usnesení, smlouvy, vypořádání práv a harmonogram.',signal='Doložená příprava',refs=[(STADIUM,'PDF s. 1 – tři varianty dalšího postupu')],counter='Podporu 50 zastupitelů z roku 2025 nelze připsat jen této kampani.')
add('K05-02','Otevřená radnice a kontrola','Koláčný navrhl konkrétní kontrolní postup, ale zdržení u jiné varianty není odmítnutí kontroly jako takové.','transparency','Programové heslo potřebuje pravidla zveřejňování a vymezení kontrol. Doložené hlasování rozlišuje pracovní skupinu a externí posouzení.','Konkrétní standard zveřejňování a doložené výsledky kontrol.',signal='Doložená iniciativa',counter='Lídryně Janulíková v daném zastupitelstvu nehlasovala; hlas kandidáta není její osobní hlas.')
add('K05-03','2 000 obecních bytů do roku 2035','Cíl přesahuje jedno volební období a kampaň nemá doložený projektový plán pro celý objem.','housing','Rok 2035 nesmíme převést na slib dokončení do roku 2030. Program chce také vyjednávat dostupné bydlení s investory; jejich souhlas není automatický.','Milníky do roku 2030, pozemky, finanční model a konkrétní smlouvy.',promise='Prosazovat nejméně 2 000 obecních nájemních bytů v dostupném režimu do roku 2035 a nepodporovat další privatizaci městských bytů.',source='bf1d45a61931b218',locator='Bydlení',votes=['Z9-25-057','Z9-32-036'],signal='Soulad u prodejů',history='Tomáš Koláčný odmítl prodej Dornychu a podpořil zrušení starého privatizačního postupu.',counter='Ochrana existujících bytů není doklad dokončení nových.')
add('K06-01','Družstevní a startovací bydlení','Kandidáti podpořili konkrétní přípravné kroky, ale tempo a objem slibované výstavby nejsou určeny.','housing','Výběr banky pro Kamenný vrch je krok k realizaci. Zářijový návrh úvěru uvádí až 1,71 mld. Kč pro 280 družstevních jednotek; to není počet již předaných bytů.','Podepsané financování, průběh stavby a předané byty.',signal='Doložená příprava',refs=[(LOAN,'PDF s. 1 – účel a limit návrhu úvěru')],counter='Kredit za přípravu patří i dalším podporujícím zastupitelům a zpracovatelům.')
add('K06-02','Aréna a další sportoviště','Financování arény podpořilo všech deset tehdy hlasujících kandidátů, ale každý další stadion vyžaduje vlastní rozhodnutí.','budget','U arény je třeba oddělit investiční dokončení od dlouhodobého provozu; Lužánky mají samostatné právní a finanční podmínky.','Provozní bilance arény a smluvní cesta dalších sportovišť.',signal='Soulad s hlasováním',refs=[(STADIUM,'PDF s. 1 – Lužánky: další postup')],counter='Pavel Jankůj tehdy neměl mandát; nová lídryně také nehlasovala. Společný hlas neprokazuje autorství celé investice.')
add('K06-03','Posunout nový železniční uzel','Majetkový krok je doložený, dokončení státní železnice však není v rukou samotného města.','rail','Správa železnic uvádí předpoklad stavebních prací 2028–2035. Slib posunout projekt nelze zaměnit za dokončit ho do konce období.','Dohodnuté městské milníky a financování návazné infrastruktury.',signal='Doložená příprava',refs=[(RAIL,'harmonogram 2028–2035')],counter='Závislost na státu nečiní spolupráci města nesmyslnou; omezuje pouze záruku celého výsledku.')
add('K06-04','Strom a stín do pěti minut','Prostorový závazek jde měřit, ale chybí mapa výchozího stavu a financovaný plán doplnění.','public','Pět minut chůze musí mít jednotný výklad a dostupný cíl. Strom a skutečný letní stín nejsou automaticky totéž.','Mapa dostupnosti, seznam deficitních míst a financování výsadby i péče.',counter='Neexistence mapy v našem rozboru není důkaz, že taková mapa nikde neexistuje.')
add('K06-05','Dokončit Janáčkovo centrum','Podpora celého rozpočtu neprokazuje dokončení koncertního sálu.','budget','Je nutné spojit stav zakázky, stavební harmonogram a financování včetně vybavení. Tento audit nepokrývá všechny smluvní podmínky centra.','Ověřený aktuální harmonogram a smluvně pokryté zbývající práce.',signal='Jen nepřímý důkaz',counter='Rozpočtová návaznost existuje, konkrétní výsledek se musí ověřit na stavbě.')
add('K07-01','Městské nájemní byty a opravy','Město má nástroje, ale bez počtu bytů a termínu je úspěch slibu obtížné ověřit.','housing','Rozsah oprav, financování a připravenost pozemků nejsou v tomto závazku vyčísleny. Dřívější mandát lídra není důkaz realizace dnešního slibu.','Počet oprav a novostaveb, termíny a rozpočet.',signal='Málo konkrétní',counter='Chybějící osobní hlasy z posledního období nejsou důkaz nečinnosti.')
add('K07-02','Více krizového ubytování a denních center','Město může služby podpořit, ale nejsou určeny kapacity ani trvalé provozní financování.','budget','Vedle nemovitosti je třeba provozovatel, pracovníci a návaznost na síť sociálních služeb; investiční dotace nehradí automaticky budoucí provoz.','Kapacitní plán, provozovatel a víceleté financování.',counter='Slib je v oblasti, kterou město může ovlivnit; není doložen jako nemožný.')
add('K07-03','Lepší MHD a návaznost spojů','Lídr dříve prosazoval levnější MHD, ale stanovisko není důkaz zavedení dnešních dopravních změn.','transport','Koordinace městské a regionální dopravy potřebuje dohodu objednatelů; bez seznamu změn nelze určit náklady ani přínos.','Konkrétní linky, intervaly, dohody a rozpočet.',signal='Starší doložený postoj',counter='Článek politika je důkaz postoje, nikoliv neutrální vyhodnocení dopravní politiky.')
add('K08-01','Připravit další tisíc bytů','Konkrétní příprava je doložena, nezávislé ověření součtu tisíce a financování další tisícovky však chybí.','housing','Připravit není postavit. Lednový materiál uvádí projekty v různých fázích; červnový hlas vybírá banku a zářijový materiál teprve předkládá úvěrovou smlouvu.','Veřejný seznam započítaných projektů se stejnou definicí připravenosti.',signal='Smíšená praxe',refs=[(HOUSING,'PDF s. 3–5 – projekty a stupně přípravy'),(LOAN,'PDF s. 1 – návrh úvěru')],history='Kandidáti podpořili Kamenný vrch. Sedm zároveň hlasovalo pro prodej Dornychu; všech devět později pro zrušení starého privatizačního postupu.',counter='Pozdější omezení prodejů je protidůkaz proti jednoduchému tvrzení, že se postoj vůbec nezměnil.',promise='Připravit nejméně další tisíc bytů; městské pozemky a budovy používat pro dostupné bydlení místo rozprodeje.',votes=['Z9-25-057','Z9-32-036','Z9-36-071'])
add('K08-04','Levnější MHD a jiný postup u nádraží','Tarif město ovlivňuje, ale státní peníze na nádraží nemůže samo převést na bydlení.','rail','Program navrhuje MHD zdarma do 15 a od 65 let, zachování vlaků v centru a přednost VRT. Správa železnic už připravuje jinou schválenou variantu; změna vyžaduje dohodu se státem, náklady a nový harmonogram.','Oddělený rozpočet tarifu a doložená dohoda se státem o železniční variantě.',promise='Zavést bezplatnou MHD do 15 a od 65 let, dát přednost VRT před překládáním nádraží a prosazovat severojižní kolejovou dráhu.',source='bc367294a3a2b4cb',locator='Pohyb klidem',votes=['Z9-18-088'],refs=[(RAIL,'schválený projekt železničního uzlu'),(MHD,'současné věkové slevy')],signal='Závisí na státu',history='Dřívější majetkový krok k železničnímu uzlu není hlas o této nové variantě.',counter='Prosazovat změnu státního projektu možné je; nelze ji ale vydávat za jednostranně rozhodnutelný úkol Brna.')
add('K08-05','Soutěže a otevřená městská data','Pravidla otevřených dat byla schválena, úplné plnění a užití soutěží u všech klíčových projektů ověřeno není.','transparency','Rozhodující jsou skutečně zveřejněná data a zadání konkrétních soutěží, ne jen schválený rámec.','Seznam klíčových projektů, soutěží a aktualizovaných datových sad.',promise='U klíčových projektů používat architektonické soutěže a rozvíjet otevřená data města.',source='bc367294a3a2b4cb',locator='Město klidem',votes=['Z9-09-016'],signal='Doložený rámec',history='Zastupitelstvo schválilo pravidla otevřených dat městských společností; osobní hlasy jsou níže.',counter='Schválený rámec je konkrétní krok, ale není automaticky úplným splněním.')
add('K08-06','Více strážníků v ulicích','Rozhodnutí o penězích samo nezajistí nábor a udržení lidí.','budget','Počet nových strážníků, směny a dlouhodobé mzdové náklady nejsou v tomto programovém bodu určeny.','Náborový plán, cílové počty ve službě a financování.',promise='Posílit počet strážníků v ulicích.',source='bc367294a3a2b4cb',locator='Život klidem – bezpečnost',history='V ověřeném výběru není osobní rozhodnutí odpovídající konkrétnímu navýšení.',counter='Město vlastní policii řídí; nejde o slib ovládat Policii ČR.')
add('K08-07','Protipovodňová opatření a břehy přehrady','Jde o reálné městské úkoly, ale odkanalizování břehů je zatím slib přípravy.','public','Stavby závisí na majetku, projektové dokumentaci, povoleních a financování. Nábřeží má navíc spojit protipovodňovou funkci s veřejným prostorem.','Projektové a finanční milníky jednotlivých staveb.',promise='Pokračovat v protipovodňových opatřeních a připravit odkanalizování obou břehů přehrady.',source='bc367294a3a2b4cb',locator='Voda klidem',votes=['Z9-20-040'],signal='Jen nepřímý důkaz',history='Hlas o průběžných informacích o protipovodňových stavbách není doklad dokončení ani postoj ke každé stavbě.',counter='Program sám u kanalizace slibuje přípravu, nikoliv dokončení.')
add('K09-01','Doprava, bezpečnost a hospodaření','Celostátní hesla neříkají, jaký konkrétní výsledek má Brno dostat.','budget','Samostatný detailní brněnský program nebyl v ověřených zdrojích nalezen; bez místních cílů není možné určit cenu ani termín.','Aktuální brněnské závazky s měřitelnými cíli.',signal='Málo konkrétní',history='Tomáš Kratochvíl byl v roce 2014 zvolen městským radním pro správu městských účastí; absence hlasů 2022–2026 není absence starší zkušenosti.',counter='Zkušenost z města i Bystrce je relevantní, ale sama neověřuje obsah dnešního obecného programu.')
add('K10-01','Omezit pyrotechniku','Brno už pyrotechniku reguluje; slib zákazu potřebuje přesně vymezit další rozsah a zákonné možnosti.','public','Nelze směšovat zákaz na vybraných místech, typy výrobků a všechna použití. Konkrétní návrh musí projít právním posouzením a většinou zastupitelstva.','Návrh vyhlášky s přesným rozsahem a ověření aktuálních zákonných mezí.',signal='Existující nástroj',counter='Hlasování dosavadních zastupitelů není osobním výsledkem těchto tří kandidátek.')
add('K10-02','Podporovat útulky a pomoc zvířatům','Městská podpora je možná, ale nejsou určeny částky, příjemci ani způsob kontroly.','budget','Prohlášení je celostátní; podporu soukromých útulků je třeba přeložit do konkrétních brněnských grantových pravidel.','Místní dotační program a jeho finanční objem.',promise='Podporovat soukromé útulky, azyly a spolky pomáhající opuštěným a týraným zvířatům.',counter='Nová listina nemá doložený osobní hlasovací záznam; to samo nic neříká o dobrovolnické práci kandidátek.')
add('K10-03','Podporovat kastrační programy','Konkrétní nástroj je pojmenovaný, jeho brněnský rozsah ale chybí.','budget','Je nutné určit počet výkonů, cenu a spolupráci s organizacemi; podpora není totéž co nový povinný režim pro všechny chovatele.','Místní plán, poskytovatelé a rozpočet.',promise='Podporovat kastrační programy realizované soukromými organizacemi.',source='d719a868b3bfdf9b',locator='komunální prohlášení 13. 8. 2026 – kastrační programy',history='Osobní celoměstské hlasování kandidátek nebylo doloženo.',counter='Jde o nástroj, který lze financovat i bez zřizování nového útulku.')
add('K11-01','Referendum o nádraží v roce 2028','Vyhlášení referenda a změna státní stavby jsou dva různé výsledky.','referendum','Přesné znění otázky musí odpovídat samostatné působnosti města. Stát není pouhým místním referendem zavázán změnit svůj projekt.','Právně přípustná otázka, postup vyhlášení a vysvětlení důsledků obou odpovědí.',refs=[(RAIL,'státní projekt železničního uzlu')],signal='Závisí na partnerech',counter='Referendum o postoji a jednání města může mít smysl; není automaticky neplatné proto, že železnici staví stát.')
add('K12-01','Teplo levnější o 15 %','Sleva není doloženým tarifem a rozhodující je, kdo zaplatí rozdíl.','energy','Teplárny pro rok 2026 oznámily zachování cen 2025. Slib pro občany s trvalým pobytem musí vyřešit nákladovou kalkulaci a způsob přenosu úlevy ke konkrétním domácnostem.','Kalkulace, právně ověřený mechanismus a finanční krytí slevy.',refs=[(HEAT,'oznámení cen pro rok 2026')],counter='Sleva či kompenzace není předem nemožná; dosavadní stabilní tarif však neprokazuje slibovaných 15 %.')
add('K12-02','Třetí kotel SAKO','Starší vedení města nedokazuje dnešní termín kotle a tvrzená škoda není výsledkem našeho auditu.','energy','Program kritizuje opakování soutěže. Výši škody by bylo nutné ověřit porovnáním smluv, cen, podmínek a alternativ; rozdíl cen sám nestačí.','Úplná časová a finanční bilance projektu a doložený plán dostavby.',signal='Neověřené tvrzení kampaně',counter='Tajné hlasování v roce 2023 nelze připsat Vokřálovi, který tehdy neměl mandát.')
add('K12-03','Nájemné podle příjmu domácnosti','Vokřál má doloženou zkušenost se sociálním bydlením, nikoliv se zavedením tohoto plošného příjmového pravidla.','housing','Pásmo 20–35 % vyžaduje definici příjmu, pravidelnou kontrolu, postup při jeho změně a dohodu s městskými částmi. Financování oprav musí fungovat i při nižším nájemném.','Pravidla příjmového testu a model dopadu na bytový fond.',signal='Starší doložená praxe',refs=[('2cb30b541c6fc59f','Rapid Re-Housing – 50 rodin a prodloužení nájemních smluv')],history='Za Vokřálova primátorství se uskutečnil pilot Rapid Re-Housing pro 50 rodin; městská zpráva uvádí prodloužení smlouvy čtyřicáté rodině.',counter='Šlo o práci koalice, úřadu a partnerů, ne výlučný osobní výsledek primátora; jiný mechanismus neověřuje dnešní procenta.')
add('K12-04','Alespoň 150 milionů ročně pro zoo','Částka je měřitelná, ale není doloženo její víceleté krytí vedle dalších slibů.','budget','Při čtyřech celých letech jde minimálně o 600 mil. Kč investic. To je prostý součin slibu, nikoliv nezávislý stavební rozpočet; provoz a parkování jsou další otázky.','Seznam investic, rozpočet a jejich soulad s celkovým finančním plánem.',counter='Město může o podpoře své zoo rozhodovat; problém je doložení krytí a realizace, ne chybějící pravomoc.')
add('K12-05','Prevence ve školách a podpora kroužků','Financovat školní aktivity lze, slib ale musí určit počet škol a dlouhodobé mzdové náklady.','budget','Program zmiňuje 1,5–2 mil. ročně na preventivní programy a pro každou žádající školu čtyři poloviční úvazky pro kroužky. Čtyři poloviční úvazky odpovídají dvěma plným na školu; celková cena není doložena.','Vyjasnění rozsahu preventivních grantů, počtu škol a ceny úvazků.',promise='Financovat školní prevenci a na požádání školy dva poloviční úvazky pro sportovní a dva pro ostatní kroužky.',source='b31cfa08ef916f6b',locator='PDF s. 3 – Bezpečnost',history='Odpovídající zavedený celoměstský nárok nebyl doložen.',counter='Město a městské části mají se školními programy zkušenost; automaticky však nevzniknou potřební pracovníci.')
add('K13-01','První rezidentní oprávnění zdarma','Město může cenu změnit, ale bezplatné oprávnění nevytvoří parkovací místo.','transport','Rozhodující je výpadek příjmů a další financování systému. Slib se týká prvního rezidentního oprávnění, nikoliv návštěvnického parkování nebo zrušení zón.','Finanční dopad a přesně schválený ceník.',counter='Není správné rozšiřovat slib na parkování zdarma pro každého všude.')
add('K13-02','Zrušit poplatek za odpad','Zrušení poplatku je politicky možné, náklady svozu ale musí přejít na jiný zdroj.','budget','Současná sazba je 900 Kč za rok s výjimkami. Nelze ji násobit všemi obyvateli bez zohlednění osvobození; příjem městské firmy také není automaticky volnou hotovostí města.','Vyčíslení skutečného výpadku a opakovaného krytí bez dvojího započítání úspor.',refs=[(WASTE,'sazba pro rok 2026')],counter='Služba může být financována z obecného rozpočtu; absence poplatku ji nedělá ekonomicky bezplatnou.')
add('K13-03','Veřejně prověřovat velké investice','Liptáková má starší doloženou zkušenost s expertizami, ale dnešní standard hodnocení investic není zavedený výsledek.','transparency','Je potřeba vymezit práh investice, nezávislost posouzení, zveřejnění a práci s alternativami i provozními náklady.','Závazná pravidla a první zveřejněná posouzení.',signal='Starší doložená praxe',refs=[('181504cb3366bfe7','expertizy privatizace; rozhodnutí rady 20. a 27. 1. 2015')],history='Jako první náměstkyně v roce 2015 Liptáková představovala závěry dvou objednaných právně-ekonomických expertiz privatizace.',counter='Zakázka na expertizu k jinému problému není důkaz pravidelné kontroly všech velkých investic.')
add('K14-01','500 městských bytů ročně','Odborná příprava území není doklad schopnosti každoročně dokončit tento objem bytů.','housing','500 bytů za každý celý rok znamená za čtyři roky 2 000 bytů; jde o přepočet slibu, ne potvrzenou kapacitu. Je nutné určit projekty, cenu, povolení a dodavatele.','Roční plán dokončování, financování a rozlišení nových bytů od oprav.',refs=[(HOUSING,'přílohy s projekty a předpokládanými termíny')],counter='KAM zajišťuje odbornou přípravu; vydání územního plánu ani zkušenost architekta nejsou samy stavebním výsledkem.')
add('K14-02','Zahájit nádraží a připravit podzemku','Zahájení odpovídá předpokládanému období státního projektu, jeho termín však město samo nezaručí.','rail','Program rozlišuje zahájení nádraží a přípravu podzemní dráhy; neslibuje hotové metro do roku 2030. U okruhu a železnice jsou nezbytní státní partneři.','Společné milníky investorů a městské financování návazných staveb.',signal='Odborná zkušenost',refs=[(RAIL,'předpoklad realizace 2028–2035'),('1cde5a071f4d126b','Sedláček: ředitel KAM od roku 2016')],history='Sedláček vedl Kancelář architekta města; doložená profesní role není osobní hlas v zastupitelstvu.',promise='Zahájit nové hlavní nádraží a přestavbu uzlu; rozvíjet tramvaje a připravit stavbu podzemní dráhy.',counter='Spolupráce města se státem je skutečná kompetence; závislost na partnerovi není sama důkaz nemožnosti.')
add('K14-03','Tempo 1 200 míst pro seniory ročně','Číslo je výrazné, ale program neprokazuje souběžnou stavební a personální kapacitu.','budget','Tempa chce program dosáhnout během období. Bydlení pro seniory není automaticky lůžko pobytové sociální služby; tyto kapacity nelze míchat.','Rozdělení typů míst, seznam lokalit, financování a plán pracovníků.',promise='Během období dosáhnout ročního tempa výstavby 1 200 nových míst v bydlení pro seniory.',source='46b0b1680eaf247b',locator='PDF s. 2 – Senioři a sociální péče',history='Realizace této kapacity dnešními kandidáty nebyla doložena.',counter='Není slíbeno 1 200 dokončených míst hned v prvním roce.')
add('K14-04','Tři nové základní školy','Lokality jsou konkrétní, dokončení však vyžaduje projekty, peníze a spolupráci se zřizovateli.','budget','Sadová, Trnitá a Zbrojovka jsou tři různé investice s vlastní připraveností. Je třeba oddělit otevření školy od zahájení stavby.','Aktuální stav každé školy, termín otevření a smluvní financování.',promise='Postavit tři základní školy: Sadová, Trnitá a Zbrojovka.',source='46b0b1680eaf247b',locator='PDF s. 2 – Školství',history='Přípravu lokalit nelze vydávat za již postavené školy.',counter='Konkrétní lokality umožňují budoucí kontrolu lépe než obecný slib více škol.')
add('K14-05','Podmínky pro 10 000 kvalifikovaných míst','Město může připravit podmínky, zaměstnání však vytvářejí také soukromí investoři.','budget','Program požaduje i dva high-tech investory po nejméně 500 místech. Nová místa je třeba odlišit od přesunů firem; plnění závisí na ekonomice a náboru.','Dohody investorů, definice nového místa a městské kroky s termíny.',promise='Vytvořit podmínky pro 10 000 vysoce kvalifikovaných pracovních míst a přivést dva high-tech investory, každého s alespoň 500 místy.',source='46b0b1680eaf247b',locator='PDF s. 1 – Ekonomika a inovace',history='Odpovídající zajištěné investice nejsou v tomto posouzení doložené.',counter='Slib zní vytvořit podmínky; nepřepisujeme jej na zaměstnat 10 000 lidí přímo magistrátem.')
add('K15-01','Odmítnout lanovku do kampusu','Podpora veřejného projednání ukazuje kontrolu projektu, nikoliv jeho zastavení.','transport','Vlastní nesouhlas mohou zastupitelé vyjádřit, zastavení projektu ale závisí na většině a existujících závazcích.','Přímý návrh a hlasování o dalším osudu projektu včetně nákladů změny.',signal='Jen nepřímý důkaz',counter='Všichni tři podpořili veřejné projednání; tím se ale nerozhodovalo o výstavbě.')
add('K15-02','Neprodávat byty a stavět dostupné bydlení','Odpor k prodeji je doložený, výstavbu však nelze potvrdit jen hlasováním proti převodům.','housing','Podpora banky pro Kamenný vrch a odpor k vložení stávajícího domu Mostecká 16 do družstva jsou rozdílné postoje ke dvěma projektům, nikoliv nutně rozpor.','Pravidla majetkové ochrany a financovaný plán výstavby.',signal='Soulad u prodejů',counter='U dvou červnových hlasování byl jeden ze tří kandidátů nepřítomen; jeho hlas nevymýšlíme.')
add('K15-03','Další kotel spalovny','Odmítnutí tajného hlasování je doložené, následný tajný hlas ani budoucí dokončení z něj neplynou.','energy','Investice potřebuje schválené financování, soutěž a termín; tyto podmínky nejsou nahrazeny programovou podporou.','Aktuální smluvní a finanční plán dostavby.',signal='Jen nepřímý důkaz',counter='Dva kandidáti hlasovali proti tajné proceduře, jeden nebyl přítomen; nejde o tři veřejné hlasy pro kotel.')
add('K15-04','Stadion se soukromým investorem','Podmíněná podpora a požadavek právně čistého postupu navazují na rozhodování, finální smluvní řešení ale není doloženo.','budget','Soukromý investor neznamená nulové městské náklady; záleží na pozemcích, infrastruktuře a závazcích smluv.','Ověřené usnesení a konečná smlouva včetně rizik pro město.',signal='Doložená příprava',refs=[(STADIUM,'PDF s. 1 – posudky a varianty dalšího postupu')],counter='Podpora zjištění podmínek není automaticky souhlas s každou pozdější nabídkou.')
add('K15-05','Vracet parkovací příjmy do čtvrtí','Rozpočtové pravidlo lze přijmout, ale nejsou určeny podíl a započítávané náklady.','budget','Hrubé příjmy parkování nejsou částka volná po úhradě provozu. Mechanismus musí být slučitelný s výdaji, které dnes tyto peníze financují.','Jasný podíl, základ výpočtu a schválené rozdělení prostředků.',counter='Nejde o automatický zákonný nárok lokality; město však takové pravidlo může politicky prosadit.')
add('K16-01','Více strážníků','Město může policii financovat, ale kampaň nedoložila počet nových lidí a plán náboru.','budget','Personální kapacitu tvoří nábor, výcvik a udržení pracovníků, nejen schválená tabulková místa.','Počet strážníků ve směnách, mzdové krytí a harmonogram.',promise='Zvýšit počet strážníků v brněnských ulicích.',counter='Celkový hlas o rozpočtu není hlas o tomto konkrétním navýšení.')
add('K16-03','Nepřetržité úklidové čety','Nepřetržitý provoz je konkrétní závazek, ale chybí rozsah služby a směnový rozpočet.','budget','Je nutné určit území, počet čet, smluvního provozovatele a vztah ke stávajícímu úklidu města a částí.','Provozní model na 24 hodin, financování a pravidla dostupnosti.',promise='Zřídit nepřetržité úklidové čety pro pořádek a čistotu města.',source='b0b7232944a526b8',locator='zahájení kampaně 31. 8. 2026 – vyjádření Jiřího Kmenta',history='Odpovídající osobní návrh či uskutečněný nepřetržitý provoz nebyl v podkladech ověřen.',counter='Vyjádření zachytil zpravodajský zdroj; nejde o detailní vlastní program.')
add('K16-02','Stacionář pro lidi bez domova','Inspirace jiným městem není hotový brněnský projekt ani financovaná služba.','budget','Vedle stavby je třeba stanovit klienty, kapacitu, dobrovolnost služby, provozovatele a sociální pracovníky.','Lokalita, kapacita, provozní pravidla a dlouhodobé financování.',counter='Město může sociální službu zřídit či podpořit; chybějící detaily nejsou důkaz její nemožnosti.')

# Doplnění po nalezení datovaného rozhovoru; výběr měníme kvůli novému
# programovému zdroji, nikoli kvůli příznivému/nepříznivému hlasování.
INTERVIEW='e361ef775f79a891'
CAMPAIGNS[1].update(summary='Bytová výstavba je jasná priorita, ale „stovky bytů“ bez termínu a projektů ještě nejsou realizovatelný plán.',selection='Aktualizace: zářijová odpověď lídra upřesňuje srpnový obecný rámec o bydlení. Tři odlišné konkrétní hlavní závazky nejsou doložené.')
CLAIMS=[c for c in CLAIMS if c['key'] not in ['K01-01','K09-01']]
add('K01-02','Stovky nových obecních bytů','Priorita je konkrétnější než srpnové oznámení, ale rozsah a termín zůstávají otevřené.','housing','Lídr připouští úvěr vztažený k rozpočtu města. Bez ceny projektů, splatnosti a výnosů nelze posoudit udržitelnost; nájemné nezaručuje samofinancování celé stavby.','Seznam projektů, počet dokončených bytů a finanční plán.',promise='Prosazovat výstavbu stovek obecních bytů a připustit úvěrové financování.',source=INTERVIEW,locator='otázka 1 – Zdeněk Slavík',history='Nikdo z dnešní kandidátky neměl celoměstský mandát 2022–2026; bývalé hlasy SOCDEM nepřenášíme.',signal='Málo konkrétní',counter='Novější odpověď již uvádí bytovou prioritu; závěr nelze stavět jen na starším obecném oznámení.')
CAMPAIGNS[9].update(summary='Lídr má starší městskou praxi a konkrétní školní návrh, u bezpečnosti a rychlejších oprav ale chybí cíle i finanční plán.',selection='Aktualizace podle zářijových odpovědí lídra: bezpečnost, kratší opravy komunikací a nabídka školního pohybového projektu.')
add('K09-02','Bezpečnost a veřejný pořádek','Priorita neurčuje, jakou změnu služby mají lidé poznat.','budget','Chybí cílové personální kapacity a vyhodnocení konkrétních problémových míst. Zkušenost starosty sama nenahrazuje městský plán.','Měřitelné cíle a náklady opatření.',promise='Posílit bezpečnost a důsledněji řešit narušování veřejného pořádku.',source=INTERVIEW,locator='otázka 1 – Tomáš Kratochvíl',history='Tomáš Kratochvíl byl městským radním pro správu městských účastí; neplést se současným Petrem Kratochvílem.',refs=[('96ab5768e37aec62','vedení města zvolené 25. 11. 2014')],counter='Praxi má; účinek tohoto dosud obecného opatření ale není doložen.',signal='Málo konkrétní')
add('K09-03','Kratší opravy a uzavírky','Koordinace může pomoci, všechny stavby a lhůty však město neřídí.','transport','Zrychlení vyžaduje součinnost vlastníků sítí a komunikací; termíny mohou ovlivnit technické podmínky, soutěže i povolení.','Seznam procesních změn a měření délky oprav.',promise='Zkrátit opravy komunikací a související uzavírky.',source=INTERVIEW,locator='otázka 1 – Tomáš Kratochvíl',history='Srovnatelný celoměstský výsledek zkrácení oprav není doložen.',counter='Není správné připisovat městu každou uzavírku na státní či krajské silnici.')
add('K09-04','Pohybový projekt pro všechny školy','Nabídnout program lze snáze než zajistit zapojení a personál všech škol.','budget','Lídr odkazuje na fungování projektu v Bystrci. V tomto rozboru nemáme nezávislé vyhodnocení jeho rozsahu a výsledků, proto jej vedeme jako tvrzení kampaně.','Doklady výsledků pilotu a finanční plán rozšíření.',promise='Nabídnout všem brněnským školám projekt Pohybově aktivní školy.',source=INTERVIEW,locator='otázka 1 – Tomáš Kratochvíl',history='Kampaň uvádí bystrcký pilot; jeho účinek zde nezávisle nepotvrzujeme.',counter='Slib nabídnout není slib povinné účasti všech škol.',signal='Uváděný pilot')
CAMPAIGNS[4]['political']='Trojan připouští ODS i Piráty; Zlatušková i Zemek ale spolupráci s ANO odmítají. Jednostranná ochota není koaliční cesta.'
CAMPAIGNS[6]['political']='Zlatušková odmítá ANO, SPD a Motoristy. Dosavadní koalice proto není automatickým modelem dalšího období.'
CAMPAIGNS[15]['political']='Zemek odmítá koalici s ANO, SPD a Motoristy; počet mandátů zbývajících partnerů není doložený.'
CAMPAIGNS[3]['political']='Vencovská preferuje Piráty, Lidovce a Starosty a Za Lužánky; odmítá SPD a Motoristy. Většinu těchto partnerů zatím neznáme.'
for n in [3,4,6,15]: CAMPAIGNS[n]['political_refs']=[(INTERVIEW,'otázka 2 – odpovědi lídrů 12. 9. 2026')]
for c in CLAIMS:
 if c['key']=='K07-03':c['references'].append(('56cbbde5c86fe0d9','PDF s. 2 – stanovisko Martina Říhy k levnější MHD, listopad 2016'))
 if c['key']=='K08-01':
  c['practical']+=' Návrh úvěru zároveň obsahuje závazek města při dočasné neobsazenosti zajistit chybějící splátky: úvěr družstva tedy neznamená nulové riziko města.'
 if c['key']=='K06-02':
  c['references'].append(('d4b6a96177052aff','zpráva 10. 9. 2026 – prohlídky před dokončením'))
  c['history']='Všech deset nynějších kandidátů s tehdejším mandátem schválilo financování arény. Zářijová zpráva města nabízí prohlídky stavby před dokončením; hotový provoz z ní nevyvozujeme.'
 if c['key']=='K06-05':
  c.update(why='Stavba skutečně pokračuje, ale termín dokončení zůstává plánem a otevření se očekává až v roce 2029.',signal='Doložená realizace',history='Městský projektový přehled uvádí dokončení 2028 a otevření 2029. Zpráva z března 2026 dokládá konkrétní stavební práce, nejen hlas o rozpočtu.',practical='Podzemní části a přeložky již mají doložený postup. U dokončení zbývá stavební a dodavatelské riziko; termín v projektovém přehledu není záruka.',references=[('1f563a1d4b813e15','hlavička projektu – dokončení 2028, otevření 2029'),('822e974afd12198b','stav prací 6. 3. 2026')])

OLDER_LEADERS={
7:('Dřívější zastupitel ZMB; doložený postoj k MHD v roce 2016.', [('56cbbde5c86fe0d9','PDF s. 2 – Martin Říha, opoziční zastupitel')]),
9:('V roce 2014 zvolen městským radním pro správu městských účastí.', [('96ab5768e37aec62','Tomáš Kratochvíl, vedení 2014–2018')]),
12:('Primátor zvolený v roce 2014; doložená zkušenost se sociálním bydlením.', [('96ab5768e37aec62','Petr Vokřál, primátor'),('2cb30b541c6fc59f','Rapid Re-Housing')]),
13:('První náměstkyně zvolená v roce 2014; doložené odborné posudky privatizace.', [('96ab5768e37aec62','Klára Liptáková, první náměstkyně'),('181504cb3366bfe7','expertizy 2015')]),
}

# Realizační podklady ověřené odděleně od hlasování; neplést existující
# smlouvu, budoucí dokončení a osobní zásluhu jednoho kandidáta.
for c in CLAIMS:
 if c['key'] in ['K02-05','K12-02','K15-03']:
  c['references'] += [('cad8eb04b0609826','oznámení uzavřené smlouvy na modernizaci ZEVO za 5,4 mld. Kč'),('88da08b32dbbccce','16. 6. 2025 – tehdejší plán dokončení v květnu 2028')]
  c['practical']='SAKO oznámilo podepsanou smlouvu za 5,4 mld. Kč a podporu z Modernizačního fondu; dřívější sdělení uvádělo květen 2028. Projekt tedy není jen volební nápad. Zbývá ověřit aktuální plnění harmonogramu a finanční rizika; oznámení firmy není nezávislý audit.'
  c['history']=(c['history'] or 'Vybrané osobní hlasy dokládají postoj k tajné proceduře, nikoliv následnou tajnou volbu.')+' Vedle toho je doloženo oznámení SAKO o uzavření realizační smlouvy.'
  c['change']='Aktuální milníky provádění podepsané smlouvy a finanční bilance; u tvrzené škody také porovnání obou zadání a alternativ.'
  c['signal']='Podepsaná smlouva projektu'
  if c['key']!='K12-02':c['why']='Projekt už má podepsanou smlouvu; dokončení není nový nápad kampaně a samotné osobní zásluhy z tajné volby nepoznáme.'
 if c['key'] in ['K02-02','K03-01','K06-01','K08-01']:
  c['references'].append(('67608a0aa50e0c9a','15. 7. 2026 – podpis smlouvy se zhotovitelem 353 bytů'))
  c['practical']+=' V červenci 2026 byla oznámena podepsaná smlouva se zhotovitelem 353 bytů na Kamenném vrchu; projekt má tedy i realizační krok, nikoliv jen politický příslib.'
  if c['key']=='K08-01':c['history']+=' Karin Podivinská je uvedena mezi signatáři červencové smlouvy.'
  if c['key']=='K03-01':c['history']+=' Jana Drápalová jako starostka Nového Lískovce spolupodepsala smlouvu na Kamenný vrch; jde o konkrétní jinou veřejnou roli, ne samostatný audit městské části.'
 if c['key']=='K14-04':
  c['references'].append(('6dee5553d4c4aded','rok 2022 – zadání architektonické soutěže Sadová a role městského architekta'))
  c['history']='Sedláček jako městský architekt veřejně podporoval soutěž na Sadovou už v roce 2022. Projekt tedy má starší přípravu; tento podklad nepotvrzuje dnešní stav povolení ani dokončení všech tří škol.'
  c['signal']='Starší doložená příprava'


# Metodika 2: opora slibu v důkazech, nikoli prognóza výsledku voleb.
# Každé zařazení je výslovné; žádný výchozí stav ani cílový poměr barev.
EVIDENCE_ASSESSMENTS = {
 'K01-02': ('bez_opory', 'Stovky bytů jsou prioritou, ale v podkladech chybí termín, seznam projektů i propočet financování.'),
 'K02-01': ('podminene', 'Systém slev existuje a kampaň nabízí propočet, jeho krytí však závisí na přibližně 10 tisících nově přihlášených obyvatel.'),
 'K02-02': ('podminene', 'Příprava bydlení i smlouva na Kamenný vrch jsou doložené, pro celý počet oprav a novostaveb ale chybí projektový plán a aktuální výchozí data.'),
 'K02-05': ('podlozeno', 'Dokončení navazuje na oznámenou realizační smlouvu SAKO za 5,4 mld. Kč a podporu z fondu; dokládá to postup projektu, nikoli výlučnou zásluhu kandidátky.'),
 'K02-06': ('bez_opory', 'Slib má termín i požadovaný výsledek, ale nemáme doložený systém odpovědností, personální plán ani dosavadní splnění této garance.'),
 'K03-01': ('podminene', 'Drápalová doložitelně kontrolovala bytová data a spolupodepsala smlouvu na Kamenný vrch; opravy i slíbené budoucí tempo ještě potřebují úplný plán.'),
 'K03-02': ('podminene', 'Bezplatnou přepravu lze rozšířit v existujícím tarifním systému, podmínkou je vyčíslit a uhradit nové slevy pro všechny uvedené skupiny.'),
 'K03-03': ('podlozeno', 'Drápalová a Flamiková tajnou proceduru skutečně odmítly a svůj další hlas mohou ovlivnit samy; doklad se netýká všech nových kandidátů ani všech minulých hlasování.'),
 'K03-04': ('podminene', 'Participativní rozpočet již funguje, zvýšení na 50 milionů ale vyžaduje novou rozpočtovou alokaci a jasná pravidla jejího počítání.'),
 'K03-06': ('bez_opory', 'Tento obecný slib nemá v rozboru doložený rozsah výsadeb, rozpočet péče ani měření výsledného stínu.'),
 'K04-01': ('bez_opory', 'Podklady dokládají projednávání analýz, nikoli osobní podporu stavby ani společný finanční a povolovací plán tramvají a lanovky.'),
 'K04-02': ('bez_opory', 'Bez vymezení „zbytečných“ prodejů nelze slib ověřovat; dosavadní hlasy navíc zahrnují prodej Dornychu i pozdější omezení privatizace.'),
 'K04-03': ('podminene', 'Příbuzný systém voucherů už existuje, nový příspěvek 1 000 Kč však potřebuje vlastní pravidla nároku a rozpočtové krytí.'),
 'K05-01': ('podminene', 'Stadion má širokou podmíněnou podporu zastupitelstva, k výstavbě ale stále chybí ověřené konečné smluvní a finanční řešení.'),
 'K05-02': ('podlozeno', 'Koláčný předložil konkrétní návrh kontroly vánočních trhů; je to doložená iniciativa jednoho kandidáta, nikoli důkaz hotového auditu nebo otevřenosti celé radnice.'),
 'K05-03': ('podminene', 'Koláčného hlasy odpovídají odmítání privatizace, výstavba 2 000 bytů do roku 2035 však vyžaduje dosud nedoložený projektový a finanční plán.'),
 'K06-01': ('podminene', 'Podpora přípravy a podepsaná smlouva na Kamenný vrch dávají bydlení konkrétní základ, tempo oprav a rozsah celého programu ale zůstávají neurčené.'),
 'K06-02': ('podminene', 'Financování arény i stavba jsou doložené, celý balík sportovišť však zahrnuje také stadion s dosud neuzavřenými podmínkami.'),
 'K06-03': ('podminene', 'Městský majetkový krok a státní příprava dávají uzlu reálný základ, jeho posun ale vyžaduje součinnost Správy železnic a státu.'),
 'K06-04': ('bez_opory', 'Pětiminutová dostupnost stínu je měřitelný slib, ale chybí výchozí mapa a financovaný plán, který by jeho splnění doložil.'),
 'K06-05': ('podlozeno', 'Janáčkovo centrum má doložené stavební práce a plán dokončení v roce 2028; jde o pokračující městský projekt, nikoli zaručený termín nebo osobní výsledek nové lídryně.'),
 'K07-01': ('bez_opory', 'Podpora městských bytů zatím nemá v podkladech počet, termín ani projektový plán, podle kterého by šel výsledek ověřit.'),
 'K07-02': ('bez_opory', 'Rozšíření sociálních služeb nemá doložené kapacity, konkrétní projekty ani trvalé provozní financování.'),
 'K07-03': ('bez_opory', 'Starší Říhovo stanovisko dokládá zájem o levnější MHD, ne provedené změny návaznosti spojů ani plán dnešního slibu.'),
 'K08-01': ('podminene', 'Podivinská spolupodepsala smlouvu na Kamenný vrch, příprava další tisícovky ale nemá ověřený součet a družstevní úvěr může nést i riziko města.'),
 'K08-04': ('podminene', 'Slevy MHD město ovlivňuje, změna železničního projektu a přesun státních peněz však závisejí na dohodě se státem.'),
 'K08-05': ('podminene', 'Schválená pravidla otevřených dat jsou konkrétní krok, jejich plnění a soutěže u všech klíčových projektů však ověřené nejsou.'),
 'K08-06': ('bez_opory', 'Pro více strážníků v ulicích nemáme doložený cílový počet, náborový plán ani odpovídající osobní rozhodnutí.'),
 'K08-07': ('podminene', 'Protipovodňové stavby mají doložené projednávání, příprava kanalizace obou břehů ale potřebuje vlastní technické a finanční podklady.'),
 'K09-02': ('bez_opory', 'Bezpečnost je deklarovanou prioritou, ale chybějí měřitelné cíle a náklady; starší funkce lídra tento plán nenahrazuje.'),
 'K09-03': ('bez_opory', 'Kratší uzavírky zatím nemají doložený soubor procesních změn ani měření a město navíc neřídí všechny investory.'),
 'K09-04': ('bez_opory', 'Kampaň uvádí bystrcký pilot, v podkladech ale chybí jeho nezávislé ověření a finanční plán nabídky všem brněnským školám.'),
 'K10-01': ('podminene', 'Brno již má regulaci pyrotechniky, další omezení však vyžaduje vymezit nový rozsah a postup v zákonných pravomocích města.'),
 'K10-02': ('bez_opory', 'Podpora útulků je možným městským opatřením, ale bez částek, příjemců a pravidel jde zatím o neupřesněný příslib.'),
 'K10-03': ('bez_opory', 'Kastrační program je pojmenovaný nástroj, chybí však doložený brněnský rozsah, financování a dosavadní práce kandidátek na něm.'),
 'K11-01': ('podminene', 'Místní referendum lze prosazovat, jeho otázka musí spadat do samosprávy a výsledek sám nezmění státní železniční projekt.'),
 'K12-01': ('bez_opory', 'Sleva tepla o 15 % nemá doložený tarif ani ověřený zdroj úhrady rozdílu; současné nezvyšování ceny není touto slevou.'),
 'K12-02': ('podminene', 'Dokončení kotle má oporu v existující smlouvě SAKO, součástí sdělení je však i tvrzená škoda, kterou dostupné porovnání zakázek nepotvrzuje.'),
 'K12-03': ('podminene', 'Rapid Re-Housing za Vokřálova primátorství dokládá příbuznou praxi, nové plošné příjmové pravidlo ale potřebuje vlastní návrh a finanční krytí.'),
 'K12-04': ('bez_opory', 'Částka 150 milionů ročně je jasná, ale víceletý investiční plán a její krytí vedle ostatních slibů doložené nejsou.'),
 'K12-05': ('bez_opory', 'Školní úvazky jsou konkrétní návrh, chybí však počet zapojených škol, celkový mzdový propočet a doložený zdroj financování.'),
 'K13-01': ('podminene', 'První rezidentní oprávnění je existující služba s měnitelnou cenou, její zrušení ale vyžaduje rozhodnutí a nahrazení příjmů.'),
 'K13-02': ('podminene', 'Poplatek zrušit lze, svoz odpadu však zůstane nákladem a uváděné úspory či peníze městských firem musí prokázat trvalé krytí.'),
 'K13-03': ('podminene', 'Liptáková představovala odborné posudky privatizace, veřejné prověřování všech velkých investic ale vyžaduje širší standard, než dokládá tato starší praxe.'),
 'K14-01': ('bez_opory', 'Tempo 500 nových městských bytů ročně nemá v podkladech odpovídající projektový a finanční plán ani doloženou realizaci kandidáty.'),
 'K14-02': ('podminene', 'Zahájení nádraží navazuje na státní projektový záměr, harmonogram a návazná podzemní dráha však závisejí na dalších investorech a přípravě.'),
 'K14-03': ('bez_opory', 'Tempo 1 200 nových míst pro seniory ročně nemá doloženou stavební, finanční a podle typu služby ani personální kapacitu.'),
 'K14-04': ('podminene', 'Sadová má doloženou starší soutěžní přípravu se Sedláčkovou účastí, dokončení všech tří škol ale potřebuje ověřené projekty, povolení a peníze.'),
 'K14-05': ('bez_opory', 'Požadované počty pracovních míst a investorů nejsou podepřeny doloženými zajištěnými investicemi ani konkrétním prováděcím plánem.'),
 'K15-01': ('bez_opory', 'Hlasy pro projednání analýz dokládají kontrolu lanovky, nikoli její odmítnutí; přímý důkaz tohoto postoje v ověřeném výběru chybí.'),
 'K15-02': ('podminene', 'Odpor tří kandidátů k prodeji Dornychu i podpora části bytové přípravy jsou doložené, celý stavební program ale ještě nemá ověřené krytí.'),
 'K15-03': ('podlozeno', 'Další kotel má oznámenou realizační smlouvu SAKO a podporu z fondu; oporu má postup projektu, osobní zásluhu kandidátů z tajného hlasování nevyvozujeme.'),
 'K15-04': ('podminene', 'Stadion má doložené podmíněné projednávání, rozhodující však bude konečná smlouva se soukromým investorem a vymezení rizik města.'),
 'K15-05': ('bez_opory', 'Vracení parkovacích příjmů nemá stanovený podíl ani základ výpočtu; z obecného rozpočtového hlasu nelze toto nové pravidlo doložit.'),
 'K16-01': ('bez_opory', 'Zvýšení počtu strážníků nemá doložený počet nových lidí, náborový harmonogram ani mzdové krytí.'),
 'K16-02': ('bez_opory', 'Odkaz na Svitavy nenahrazuje brněnskou lokalitu, kapacitu, provozovatele a dlouhodobé financování stacionáře.'),
 'K16-03': ('bez_opory', 'Nepřetržité čety jsou ověřitelný příslib, ale chybí územní rozsah, směnový model a provozní rozpočet.'),
}
assert set(EVIDENCE_ASSESSMENTS) == {c['key'] for c in CLAIMS}
for c in CLAIMS:
 c['evidence_status'], c['why'] = EVIDENCE_ASSESSMENTS[c['key']]
 if c['key']=='K03-03':
  c['change']='Přímo opačný procedurální hlas by oporu oslabil; další veřejné hlasy všech zvolených by rozšířily ověření za dva dosavadní kandidáty.'
 if c['key']=='K12-02':
  c['history']='Oznámení SAKO dokládá uzavření realizační smlouvy; starší Vokřálovo vedení města samo nepotvrzuje dnešní harmonogram ani výši tvrzené škody.'

CAMPAIGNS[2]['summary']='Kotel má oporu v realizační smlouvě, bydlení a levnější MHD v neuzavřených podmínkách; garance odpovědi na každý podnět zatím doložený postup nemá.'
CAMPAIGNS[3]['summary']='Odmítání tajné procedury dokládají osobní hlasy, bydlení a slevy mají konkrétní podmínky, obecný slib stínu zatím nemá ověřený rozsah.'
CAMPAIGNS[5]['summary']='Kontrolní iniciativa Koláčného je doložená, stadion a dva tisíce bytů ale nadále závisejí na smlouvách a projektových plánech.'
CAMPAIGNS[6]['summary']='Janáčkovo centrum se už staví, další rozvoj navazuje na konkrétní přípravu; pětiminutová dostupnost stínu zatím doložený plán nemá.'
CAMPAIGNS[15]['summary']='Kotel má realizační smlouvu a odpor k prodeji bytů dokládají hlasy, zastavení lanovky a vracení parkovacích příjmů zatím přímou oporu nemají.'

for c in CLAIMS:
 if c['key'] in ['K02-05','K15-03']:
  c['change']='Zrušení smlouvy, nezajištěné financování nebo zásadní skluz by oporu oslabily; ověřené plnění milníků a dokončení by ji posílily.'
 if c['key']=='K05-02':
  c['change']='Doložené výsledky kontrol a standard zveřejňování by rozšířily oporu nad jeden návrh; přímé maření obdobné kontroly by ji oslabilo.'
 if c['key']=='K06-05':
  c['change']='Zastavení stavby či ztráta financování by oporu oslabily; dokončené milníky a ověřené krytí zbývajících prací by ji posílily.'
