-- Executing the party seeding script
-- Insert Czech political parties and movements (stav: 31.07.2025; zdroj: cs.wikipedia.org)
INSERT INTO public.political_parties (name, color_hex) VALUES
  ('A DOST! PRO LEPŠÍ BUDOUCNOST', '#7f7f7f'),
  ('Aliance pro budoucnost', '#7f7f7f'),
  ('Alternativa pro Vás', '#7f7f7f'),
  ('ANO 2011', '#7f7f7f'),
  ('ANO LEPŠÍ ČESKO S MIMOZEMŠŤANY A OBČANY MOTORISTY', '#7f7f7f'),
  ('Balbínova poetická strana', '#7f7f7f'),
  ('Bezpečná země', '#7f7f7f'),
  ('BEZPEČNÉ ULICE', '#7f7f7f'),
  ('Bílinští sociální demokraté a nezávislí', '#7f7f7f'),
  ('Budoucnost', '#7f7f7f'),
  ('Budoucnost pro občany', '#7f7f7f'),
  ('Bystrčáci', '#7f7f7f'),
  ('CESTA ODPOVĚDNÉ SPOLEČNOSTI', '#7f7f7f'),
  ('COEXISTENTIA', '#7f7f7f'),
  ('Česká pirátská strana', '#7f7f7f'),
  ('Česká republika na 1. místě!', '#7f7f7f'),
  ('Česká strana národně sociální', '#7f7f7f'),
  ('Česká strana regionů', '#7f7f7f'),
  ('Česká zemědělská strana', '#7f7f7f'),
  ('Čistý kraj', '#7f7f7f'),
  ('ČSSD – Česká suverenita sociální demokracie', '#7f7f7f'),
  ('Demokratická strana zelených – ZA PRÁVA ZVÍŘAT', '#7f7f7f'),
  ('Dobrá volba 2016', '#7f7f7f'),
  ('DOMOV', '#7f7f7f'),
  ('Evolution–Mind', '#7f7f7f'),
  ('Fakt Brno', '#7f7f7f'),
  ('GEN', '#7f7f7f'),
  ('HLAS SAMOSPRÁV', '#7f7f7f'),
  ('Hnutí Generace', '#7f7f7f'),
  ('Hnutí HLAS', '#7f7f7f'),
  ('Hnutí Idealisté', '#7f7f7f'),
  ('Hnutí Kruh', '#7f7f7f'),
  ('Hnutí NEJ', '#7f7f7f'),
  ('Hnutí nezávislých, PRO-Kdyňsko', '#7f7f7f'),
  ('Hnutí občanů a podnikatelů', '#7f7f7f'),
  ('„Hnutí Praha-Kunratice“', '#7f7f7f'),
  ('Hnutí pro Havířov', '#7f7f7f'),
  ('Hnutí PRO Hodonín', '#7f7f7f'),
  ('Hnutí pro Prahu 11', '#7f7f7f'),
  ('Hnutí pro Žabiny', '#7f7f7f'),
  ('Hnutí SOL', '#7f7f7f'),
  ('HNUTÍ SPRÁVNÁ CESTA', '#7f7f7f'),
  ('Hnutí Správný stát', '#7f7f7f'),
  ('HODOŇÁCI', '#7f7f7f'),
  ('Hradecký demokratický klub', '#7f7f7f'),
  ('HRADEČÁCI', '#7f7f7f'),
  ('HRADEČTÍ PATRIOTI', '#7f7f7f'),
  ('Chomutovská koalice', '#7f7f7f'),
  ('Iniciativa občanů', '#7f7f7f'),
  ('Jasný Signál Nezávislých', '#7f7f7f'),
  ('JIHOČEŠI 2012', '#7f7f7f'),
  ('JISTOTA A BUDOUCNOST', '#7f7f7f'),
  ('Jižní Město - náš domov', '#7f7f7f'),
  ('JsmePRO!', '#7f7f7f'),
  ('Jundrováci', '#7f7f7f'),
  ('Karlovaráci', '#7f7f7f'),
  ('Karlovarská občanská alternativa', '#7f7f7f'),
  ('KDU-ČSL', '#7f7f7f'),
  ('Klidné město', '#7f7f7f'),
  ('Klub angažovaných nestraníků', '#7f7f7f'),
  ('Koalice PRO kraj', '#7f7f7f'),
  ('Komunistická strana Čech a Moravy', '#7f7f7f'),
  ('Komunistická strana Československa', '#7f7f7f'),
  ('Konzervativní strana', '#7f7f7f'),
  ('Koruna Česká (monarchistická strana Čech, Moravy a Slezska)', '#7f7f7f'),
  ('Královopolští patrioti', '#7f7f7f'),
  ('KRÁSNÁ KOPŘIVNICE', '#7f7f7f'),
  ('LEPŠÍ SEVER', '#7f7f7f'),
  ('LEPŠÍ ŽIVOT PRO LIDI', '#7f7f7f'),
  ('Levice', '#7f7f7f'),
  ('Liberálně ekologická strana', '#7f7f7f'),
  ('Liberální aliance nezávislých občanů', '#7f7f7f'),
  ('Lidé a Politika', '#7f7f7f'),
  ('Liga nespokojených', '#7f7f7f'),
  ('Malá strana velkých cílů', '#7f7f7f'),
  ('„Marek Hilšer do Senátu“', '#7f7f7f'),
  ('MÁ VLAST ČECHY MORAVA SLEZSKO', '#7f7f7f'),
  ('MĚSTO LIDEM', '#7f7f7f'),
  ('Město pro vás', '#7f7f7f'),
  ('MÍSTNÍ HNUTÍ NEZÁVISLÝCH ZA HARMONICKÝ ROZVOJ OBCÍ A MĚST', '#7f7f7f'),
  ('Moderní společnost', '#7f7f7f'),
  ('Moravané', '#7f7f7f'),
  ('Moravské zemské hnutí', '#7f7f7f'),
  ('Motoristé sobě', '#7f7f7f'),
  ('Mourek – politická strana', '#7f7f7f'),
  ('Nadační občansko-politické hnutí ReMeK', '#7f7f7f'),
  ('NAŠE čtrnáctka', '#7f7f7f'),
  ('Naše Město F-M', '#7f7f7f'),
  ('Naše Obec', '#7f7f7f'),
  ('Národně sociální strana', '#7f7f7f'),
  ('Národ Sobě', '#7f7f7f'),
  ('Národní demokracie', '#7f7f7f'),
  ('Národní obroda', '#7f7f7f'),
  ('NE 2025', '#7f7f7f'),
  ('Nestraníci', '#7f7f7f'),
  ('Nestraníci pro jižní Moravu – www.nestranici2024.cz', '#7f7f7f'),
  ('Nezávislá kandidátka', '#7f7f7f'),
  ('NEZÁVISLÁ VOLBA', '#7f7f7f'),
  ('Nezávislí', '#7f7f7f'),
  ('NEZÁVISLÍ PRO PRAHU 10 – HNUTÍ PRO LEPŠÍ DESÍTKU', '#7f7f7f'),
  ('Nová budoucnost pro Liberecký kraj', '#7f7f7f'),
  ('NOVÁ PLZEŇ', '#7f7f7f'),
  ('Nový Impuls', '#7f7f7f'),
  ('NOVÝ SEVER', '#7f7f7f'),
  ('Nový směr', '#7f7f7f'),
  ('O vás pro vás', '#7f7f7f'),
  ('Občané městských částí Opavy', '#7f7f7f'),
  ('Občané městu, město občanům', '#7f7f7f'),
  ('Občané patrioti', '#7f7f7f'),
  ('Občané pro Budějovice', '#7f7f7f'),
  ('Občanská demokratická strana', '#7f7f7f'),
  ('Občanská sounáležitost', '#7f7f7f'),
  ('Občanské fórum Beskydy', '#7f7f7f'),
  ('Osmička žije', '#7f7f7f'),
  ('Osobnosti pro kraj', '#7f7f7f'),
  ('Ostravak', '#7f7f7f'),
  ('OSVČ', '#7f7f7f'),
  ('Pardubice pro lidi', '#7f7f7f'),
  ('Patrioti České republiky', '#7f7f7f'),
  ('PATRIOTI NÁCHODA', '#7f7f7f'),
  ('Patrioti Olomouckého kraje', '#7f7f7f'),
  ('Pévéčko', '#7f7f7f'),
  ('PLUS', '#7f7f7f'),
  ('Podpora občanů', '#7f7f7f'),
  ('Politické hnutí NEZLOMNÍ', '#7f7f7f'),
  ('Pražská městská strana PRAHA SOBĚ', '#7f7f7f'),
  ('Přísaha občanské hnutí', '#7f7f7f'),
  ('PRO PLZEŇ', '#7f7f7f'),
  ('PRO Právo Respekt Odbornost', '#7f7f7f'),
  ('ProMOST', '#7f7f7f'),
  ('ProOlomouc', '#7f7f7f'),
  ('ProPce21', '#7f7f7f'),
  ('PROZMĚNU', '#7f7f7f'),
  ('Rebelové', '#7f7f7f'),
  ('REFERENDUM – Hlas Lidu', '#7f7f7f'),
  ('ROZVÍJÍME HRADEC', '#7f7f7f'),
  ('Sdružení pro Místní Správu', '#7f7f7f'),
  ('SDRUŽENÍ PRO REPUBLIKU – REPUBLIKÁNSKÁ STRANA ČECH, MORAVY A SLEZSKA', '#7f7f7f'),
  ('Sedma – strana pro Slatiňany, Škrovád, Trpišov, Kunčí, Presy, Podhůru a Kochánovice', '#7f7f7f'),
  ('SEMILÁCI', '#7f7f7f'),
  ('SEN 21', '#7f7f7f'),
  ('Severočeši.cz', '#7f7f7f'),
  ('SLAVIČÍN 2018 - sdružení nezávislých kandidátů', '#7f7f7f'),
  ('Slezská lidem', '#7f7f7f'),
  ('Směr Česká republika', '#7f7f7f'),
  ('SMS – Stát Má Sloužit', '#7f7f7f'),
  ('SNK 1 – Starostové našeho kraje', '#7f7f7f'),
  ('SNK Evropští demokraté', '#7f7f7f'),
  ('„SONOB – sdružení ochrany nájemníků a ostatního bydlení“', '#7f7f7f'),
  ('Sociální demokracie', '#7f7f7f'),
  ('Spojení demokraté – Sdružení nezávislých', '#7f7f7f'),
  ('spOLečně', '#7f7f7f'),
  ('Společně pro kraj', '#7f7f7f'),
  ('Společnost proti developerské výstavbě v Prokopském údolí', '#7f7f7f'),
  ('SPOLEHNUTÍ - SPOLEČNÉ HNUTÍ ČESKOLIPANŮ', '#7f7f7f'),
  ('SPOLEK ZA ZDRAVOU JIHLAVU', '#7f7f7f'),
  ('Správná Volba', '#7f7f7f'),
  ('Stačilo!', '#7f7f7f'),
  ('STAROSTOVÉ A NEZÁVISLÍ', '#7f7f7f'),
  ('Starostové a osobnosti pro Moravu', '#7f7f7f'),
  ('Starostové pro Liberecký kraj', '#7f7f7f'),
  ('Starostové pro občany', '#7f7f7f'),
  ('START21', '#7f7f7f'),
  ('Strakonická Veřejnost', '#7f7f7f'),
  ('Strana konzervativní pravice – Řád národa', '#7f7f7f'),
  ('Strana občanské sebeobrany', '#7f7f7f'),
  ('Strana příznivců demokracie a Tomia Okamury', '#7f7f7f'),
  ('Strana soukromníků České republiky', '#7f7f7f'),
  ('Strana státu přímé demokracie – Strana práce', '#7f7f7f'),
  ('Strana zelených', '#7f7f7f'),
  ('Středočeši2012.cz', '#7f7f7f'),
  ('Svoboda a přímá demokracie (SPD)', '#7f7f7f'),
  ('Svobodní', '#7f7f7f'),
  ('Šance pro Duchcov', '#7f7f7f'),
  ('ŠVÝCARSKÁ DEMOKRACIE', '#7f7f7f'),
  ('Ta naše Třebíč', '#7f7f7f'),
  ('Tábor 2020', '#7f7f7f'),
  ('„Tomáš Magnusek do Senátu“', '#7f7f7f'),
  ('TOP 09', '#7f7f7f'),
  ('Trikolora', '#7f7f7f'),
  ('TVŮJ KANDIDÁT', '#7f7f7f'),
  ('Unie pro sport a zdraví', '#7f7f7f'),
  ('Urza.cz: Nechceme vaše hlasy', '#7f7f7f'),
  ('ÚSTECKÉ FÓRUM OBČANŮ', '#7f7f7f'),
  ('Vaše Ústí', '#7f7f7f'),
  ('Vaši starostové', '#7f7f7f'),
  ('Victoria.cz', '#7f7f7f'),
  ('Vinohrady společně', '#7f7f7f'),
  ('Vize pro Karlovarský kraj', '#7f7f7f'),
  ('VOLBA PRO KLADNO', '#7f7f7f'),
  ('Volba pro kraj', '#7f7f7f'),
  ('Volba pro město', '#7f7f7f'),
  ('Volba pro Mladou Boleslav', '#7f7f7f'),
  ('„Volím Orlovou"', '#7f7f7f'),
  ('VOLNÝ blok', '#7f7f7f'),
  ('Volt Česko', '#7f7f7f'),
  ('Volte Pravý Blok www.cibulka.net...', '#7f7f7f'),
  ('Voluntia', '#7f7f7f'),
  ('Volyně v dolyně', '#7f7f7f'),
  ('VÝCHODOČEŠI', '#7f7f7f'),
  ('VÝZVA 2025', '#7f7f7f'),
  ('Za lepší Střekov', '#7f7f7f'),
  ('Za naše města', '#7f7f7f'),
  ('ZaRegion', '#7f7f7f'),
  ('Zdraví Sport Vzdělání 2012', '#7f7f7f'),
  ('Zlín 21', '#7f7f7f'),
  ('Zlínské hnutí nezávislých', '#7f7f7f'),
  ('Změna 2020', '#7f7f7f'),
  ('Změna pro Prahu 12', '#7f7f7f')
ON CONFLICT (name) DO NOTHING;
